import { RepoContext } from './types';

export function generateClaudeMd(ctx: RepoContext): string {
  const lines: string[] = [];

  lines.push(`# CLAUDE.md — AI Context for ${ctx.projectName}`);
  lines.push('');
  lines.push('> Auto-generated by Anchorfile. Keep this file updated as the project evolves.');
  lines.push('> Re-run `npx anchorfile init` to regenerate from current state.');
  lines.push('');

  // Project Overview
  lines.push('## Project Overview');
  const desc = ctx.description || 'No description provided.';
  lines.push(`${ctx.projectName} — ${desc}`);
  lines.push('');

  // Tech Stack
  lines.push('## Tech Stack');
  lines.push(`- **Language:** ${ctx.primaryLanguage}`);
  lines.push(`- **Frameworks:** ${ctx.frameworks.length > 0 ? ctx.frameworks.join(', ') : 'None detected'}`);
  lines.push(`- **Package Manager:** ${ctx.packageManager}`);
  lines.push(`- **Linter:** ${ctx.linter}`);
  lines.push(`- **Docker:** ${ctx.hasDocker ? 'Yes' : 'No'}`);
  lines.push(`- **CI/CD:** ${ctx.hasCI ? 'Yes' : 'No'}`);
  lines.push('');

  // Project Structure
  lines.push('## Project Structure');
  lines.push('Top-level folders:');
  if (ctx.folderStructure.length > 0) {
    for (const folder of ctx.folderStructure) {
      lines.push(`- ${folder}/`);
    }
  } else {
    lines.push('- (none detected)');
  }
  lines.push('');
  lines.push('Key files present:');
  if (ctx.keyFiles.length > 0) {
    for (const file of ctx.keyFiles) {
      lines.push(`- ${file}`);
    }
  } else {
    lines.push('- (none detected)');
  }
  lines.push('');

  // Available Scripts
  lines.push('## Available Scripts');
  const scriptEntries = Object.entries(ctx.scripts);
  if (scriptEntries.length > 0) {
    for (const [name, command] of scriptEntries) {
      lines.push(`- \`${name}\`: ${command}`);
    }
  } else {
    lines.push('No scripts defined.');
  }
  lines.push('');

  // Dependencies
  lines.push('## Dependencies');
  lines.push(`**Production:** ${ctx.dependencies.length > 0 ? ctx.dependencies.join(', ') : 'None'}`);
  lines.push(`**Dev:** ${ctx.devDependencies.length > 0 ? ctx.devDependencies.join(', ') : 'None'}`);
  lines.push('');

  // Testing
  lines.push('## Testing');
  if (ctx.hasTests) {
    lines.push(`Tests present. Framework: ${ctx.testFramework}`);
  } else {
    lines.push('No test framework detected. Consider adding tests.');
  }
  lines.push('');

  // Key Conventions
  lines.push('## Key Conventions');
  lines.push('<!-- Anchorfile detected these automatically. Expand this section manually with project-specific conventions. -->');
  lines.push(`- Package manager is ${ctx.packageManager} — do not use others`);
  lines.push(`- Primary language is ${ctx.primaryLanguage}`);
  if (ctx.primaryLanguage === 'TypeScript') {
    lines.push('- Use strict TypeScript — tsconfig strict mode');
  }
  if (ctx.linter === 'ESLint' || ctx.linter === 'Biome') {
    lines.push(`- Linting via ${ctx.linter} — run before committing`);
  }
  if (ctx.hasTests) {
    lines.push(`- Tests via ${ctx.testFramework} — maintain coverage`);
  }
  lines.push('');

  // What to Avoid
  lines.push('## What to Avoid');
  lines.push('<!-- Fill this in manually with known footguns or areas of tech debt -->');
  lines.push('- Do not modify auto-generated files without understanding the pipeline');
  lines.push('- Do not commit secrets — use .env files');
  lines.push('');

  // Files to Know
  lines.push('## Files to Know');
  lines.push('<!-- Add the most important files in this codebase here manually after generation -->');
  if (ctx.keyFiles.length > 0) {
    for (const file of ctx.keyFiles) {
      lines.push(`- ${file}`);
    }
  } else {
    lines.push('- (none detected)');
  }

  return lines.join('\n');
}
